
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue May 30 18:08:03 CST 2023
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Llave_C = 15;
  public static final int Exponente = 10;
  public static final int Llave_A = 14;
  public static final int Suma = 4;
  public static final int Numero = 9;
  public static final int ERROR = 16;
  public static final int SimbEsp = 11;
  public static final int espacioCuatro = 2;
  public static final int EOF = 0;
  public static final int Division = 7;
  public static final int Resta = 5;
  public static final int error = 1;
  public static final int Parentesis_C = 13;
  public static final int Variable = 8;
  public static final int Parentesis_A = 12;
  public static final int Igual = 3;
  public static final int Multiplicacion = 6;
  public static final int NULL = 17;
}

